on: [push]

jobs:
  native:
    runs-on: ubuntu-latest
    name: Native
    steps:
    - uses: actions/checkout@v2
    - uses: notdanilo/cross-test-action@main
      with:
        platform: native
        args: -- -- --test-threads=1
  web:
    runs-on: ubuntu-latest
    name: Web
    steps:
    - uses: actions/checkout@v2
    - uses: notdanilo/cross-test-action@main
      with:
        platform: web