on:
  pull_request:
    branches:
      - main
jobs:
  check-release:
    runs-on: ubuntu-latest
    environment: Release
    name: Check Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: notdanilo/cargo-release-action@main
        with:
          major-label: major
          minor-label: minor
          patch-label: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cargo-token: ${{ secrets.CARGO_TOKEN }}